Repository apache/incubator-annotator, pull requests merged in 2023-10, with the labels that each got.

#134 Update package.json
  package.json
  yarn.lock
Labels: dependencies, ⚙️ Refactoring

#148 #149 - Set up automated build using GitHub actions
  .github/workflows/node.js.yml
  README.md
Labels: ⚙️ Refactoring

#147 #146 - Update dependencies
  lerna.json
  package.json
  test/data-model.test.ts
  yarn.lock
Labels: dependencies, ⚙️ Refactoring

#151 Issue #150 - Include info on how to build in the README
  .github/workflows/node.js.yml
  README.md
  package.json
  web/webpack.config.js
Labels: ⭐️ Enhancement

#153 Issue #152: Provide template files for GitHub issues and PRs
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/refactoring.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: ⭐️ Enhancement
